// GERADO AUTOMATICAMENTE — não edite à mão (ver scripts/agente-conteudo.mjs).
import type { ArtigoBase } from "./_tipo";
import { artigo as a0 } from "./5-dicas-para-anunciar-seu-imovel-e-vender-rapido";
import { artigo as a1 } from "./alugar-ou-comprar-como-decidir";
import { artigo as a2 } from "./centro-de-uberlandia-guia-do-bairro";
import { artigo as a3 } from "./como-avaliar-o-preco-justo-de-um-imovel";
import { artigo as a4 } from "./como-avaliar-um-bairro-antes-de-comprar";
import { artigo as a5 } from "./como-calcular-o-aluguel-justo-do-seu-imovel";
import { artigo as a6 } from "./como-financiar-seu-primeiro-imovel-em-uberlandia";
import { artigo as a7 } from "./como-funciona-a-vistoria-de-imovel-na-locacao-guia-da-cade";
import { artigo as a8 } from "./como-usar-o-fgts-para-comprar-imovel";
import { artigo as a9 } from "./comprar-na-planta-vs-imovel-pronto";
import { artigo as a10 } from "./documentacao-para-comprar-imovel-o-checklist-completo";
import { artigo as a11 } from "./documentos-para-alugar-um-imovel-em-uberlandia-guia-da-cade";
import { artigo as a12 } from "./financiamento-caixa-vs-bancos-privados";
import { artigo as a13 } from "./granja-marileusa-guia-do-bairro";
import { artigo as a14 } from "./guia-completo-para-alugar-sem-dor-de-cabeca";
import { artigo as a15 } from "./guia-do-primeiro-apartamento-do-orcamento-a-mudanca";
import { artigo as a16 } from "./itbi-escritura-e-registro-custos-da-compra";
import { artigo as a17 } from "./jardim-karaiba-guia-do-bairro";
import { artigo as a18 } from "./minha-casa-minha-vida-em-uberlandia";
import { artigo as a19 } from "./morada-da-colina-vale-a-pena-morar-guia-da-cade";
import { artigo as a20 } from "./os-melhores-bairros-para-morar-em-uberlandia";
import { artigo as a21 } from "./quanto-custa-morar-em-uberlandia";
import { artigo as a22 } from "./reforma-que-valoriza-o-imovel-antes-de-vender";
import { artigo as a23 } from "./santa-monica-guia-do-bairro";
import { artigo as a24 } from "./seguro-fianca-caucao-ou-fiador-qual-escolher";
import { artigo as a25 } from "./tendencias-do-mercado-imobiliario-de-uberlandia-em-2026";
import { artigo as a26 } from "./tibery-guia-do-bairro-para-morar-e-alugar-guia-da-cade";

export const ARTIGOS: ArtigoBase[] = [a0, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23, a24, a25, a26];
